### ISSUE TITLE
API upload fails on AWS

### ISSUE THREAD

**Issue by sminot** [refgenomics/onecodex#13]
API installed on AWS machine requires that boto and awscli be installed manually. Error message is "Unable to locate credentials"

**Comment by boydgreenfield** [comment]
This is actually something to do with sudo and not being the root user.
Concrete to-dos:
1. Investigate and reproduce this on a couple of machines (local virtualenv
and AWS machine as non-root and root users?)
2. Catch the exception and display a more helpful warning message (note I
think this is actually awscli blowing up, which we call via `subprocess` so
we'll need to check the return code and handle it appropriately, or at
least put something in the docs here)
ᐧ

**Comment by boydgreenfield** [comment]
Closed with 6b729c3f529fcc2fa7798378b8c6c47f6e2f92a2.
